=== davidmr/seeit3d/SeeIT3D/src/seeit3d/internal/xml/internal/xsd/seeit3d.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  
   Copyright 2011 David MontaÃ±o
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 
 -->
<xs:schema targetNamespace="http://dl.dropbox.com/u/2416325/seeit3d_xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:seeit3d="http://dl.dropbox.com/u/2416325/seeit3d_xsd">
    <xs:element name="container">
        <xs:complexType>
            <xs:sequence>            	
            	<xs:element ref="seeit3d:metricsList" />
            	<xs:element ref="seeit3d:mapping" minOccurs="0"
            		maxOccurs="1" />
            	<xs:element ref="seeit3d:polycylinder" minOccurs="1"
            		maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:ID" use="required" />
            <xs:attribute name="granularityLevelName" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="related" type="xs:IDREFS" use="optional" />
            <xs:attribute name="visible" type="xs:boolean" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="entryMetricValue">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:metricName" />
                <xs:element ref="seeit3d:value" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:mappingValue" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mappingValue">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:metricName" />
                <xs:element name="visualProperty">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="COLOR" />
                            <xs:enumeration value="HEIGHT" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="metricName" type="xs:string"></xs:element>
    <xs:element name="metricsList">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:metricDescription" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>   	
    <xs:element name="metricDescription">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="NUMERIC"></xs:enumeration>
                                <xs:enumeration value="NOMINAL"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="max" type="xs:string" use="optional"></xs:attribute>
                    <xs:attribute name="categories" use="optional">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="(\w+\s?)+"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="metricsValue">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:entryMetricValue" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="polycylinder">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:name" minOccurs="1" maxOccurs="1"/>                
                <xs:element ref="seeit3d:metricsValue" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="name" type="xs:string"></xs:element>
    <xs:element name="containers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:container" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="value" type="xs:string"></xs:element>
<!--    <xs:element name="relatedList">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seeit3d:related" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="related">
    	<xs:complexType>
    		<xs:attribute name="relatedName" type="xs:IDREF"></xs:attribute>
    	</xs:complexType>    	
    </xs:element>-->
</xs:schema>

=== davidmr/seeit3d/SeeIT3D/xmlDefinition/SampleFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<seeit3d:containers xmlns:seeit3d="http://dl.dropbox.com/u/2416325/seeit3d_xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dl.dropbox.com/u/2416325/seeit3d_xsd seeit3d.xsd ">
    <seeit3d:container name="idContainer1" granularityLevelName="just this" related="idContainer2 idContainer3" visible="true">
        <seeit3d:metricsList>
            <seeit3d:metricDescription type="CONTINUOUS" max="25">ABC</seeit3d:metricDescription>
            <seeit3d:metricDescription type="CATEGORIZED" categories="text 123 ODF">DEF</seeit3d:metricDescription>
        </seeit3d:metricsList>
        <seeit3d:mapping>
            <seeit3d:mappingValue>
                <seeit3d:metricName>ABC</seeit3d:metricName>
                <visualProperty>HEIGHT</visualProperty>
            </seeit3d:mappingValue>
            <seeit3d:mappingValue>
                <seeit3d:metricName>DEF</seeit3d:metricName>
                <visualProperty>COLOR</visualProperty>
            </seeit3d:mappingValue>
        </seeit3d:mapping>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 1</seeit3d:name>
            <seeit3d:metricsValue>            
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>1.2</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>text</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 2</seeit3d:name>
            <seeit3d:metricsValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>5</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>123</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 3</seeit3d:name>
            <seeit3d:metricsValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>25</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>ODF</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
    </seeit3d:container>
    
    <seeit3d:container name="idContainer2" granularityLevelName="just this" visible="false">
        <seeit3d:metricsList>
            <seeit3d:metricDescription type="CONTINUOUS" max="25">ABC</seeit3d:metricDescription>
            <seeit3d:metricDescription type="CATEGORIZED" categories="text 123 ODF">DEF</seeit3d:metricDescription>
        </seeit3d:metricsList>
        <seeit3d:mapping>
            <seeit3d:mappingValue>
                <seeit3d:metricName>ABC</seeit3d:metricName>
                <visualProperty>HEIGHT</visualProperty>
            </seeit3d:mappingValue>
            <seeit3d:mappingValue>
                <seeit3d:metricName>DEF</seeit3d:metricName>
                <visualProperty>COLOR</visualProperty>
            </seeit3d:mappingValue>
        </seeit3d:mapping>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 1</seeit3d:name>
            <seeit3d:metricsValue>            
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>1.2</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>text</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 2</seeit3d:name>
            <seeit3d:metricsValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>5</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>123</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 3</seeit3d:name>
            <seeit3d:metricsValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>25</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>ODF</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
    </seeit3d:container>
    
     <seeit3d:container name="idContainer3" granularityLevelName="just this" visible="false">
        <seeit3d:metricsList>
            <seeit3d:metricDescription type="CONTINUOUS" max="25">ABC</seeit3d:metricDescription>
            <seeit3d:metricDescription type="CATEGORIZED" categories="text 123 ODF">DEF</seeit3d:metricDescription>
        </seeit3d:metricsList>
        <seeit3d:mapping>
            <seeit3d:mappingValue>
                <seeit3d:metricName>ABC</seeit3d:metricName>
                <visualProperty>HEIGHT</visualProperty>
            </seeit3d:mappingValue>
            <seeit3d:mappingValue>
                <seeit3d:metricName>DEF</seeit3d:metricName>
                <visualProperty>COLOR</visualProperty>
            </seeit3d:mappingValue>
        </seeit3d:mapping>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 1</seeit3d:name>
            <seeit3d:metricsValue>            
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>1.2</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>text</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 2</seeit3d:name>
            <seeit3d:metricsValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>5</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>123</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
        <seeit3d:polycylinder>
            <seeit3d:name>Poly 3</seeit3d:name>
            <seeit3d:metricsValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>ABC</seeit3d:metricName>
                    <seeit3d:value>25</seeit3d:value>
                </seeit3d:entryMetricValue>
                <seeit3d:entryMetricValue>
                    <seeit3d:metricName>DEF</seeit3d:metricName>
                    <seeit3d:value>ODF</seeit3d:value>
                </seeit3d:entryMetricValue>
            </seeit3d:metricsValue>
        </seeit3d:polycylinder>
    </seeit3d:container>
</seeit3d:containers>
